### ISSUE TITLE
Add automation support in this control

### ISSUE THREAD

**Issue by sanjaykumar5115** [shintadono/System.Windows.Forms.Ribbon#2]
Hi,
I am trying to automate the application which have the your ribbon control and this is not being identified by automation tool like (UFT and UI automation etc). so after analysis, we have found that this control doesn't support the automation. please add the support for automation

**Comment by shintadono** [comment]
Hi,
sorry for the late answer, but somehow I don't get notifications sometimes, so I didn't saw this until now.
As you might have probably noticed, this repo contains a fork of a project elsewhere. I didn't wrote the code, I don't understand most of it, I just fixed a few minor bugs, where I found them. Since I'm not using the Ribbon anymore, I don't plan to work on it, but feel free to fork or copy this repo, and implement automation, if you still need this.
